import { z } from 'zod';

const dateSchema = z.union([z.string(), z.number(), z.date()]).transform(val => {
  const d = new Date(val);
  return isNaN(d.getTime()) ? new Date() : d;
});

export const clientSyncSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  phone: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  cuit: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const planSyncSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  limit: z.number().int().default(0),
  price: z.number().default(0),
  excessPrice: z.number().default(0),
  ivaRate: z.number().default(21),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const machineSyncSchema = z.object({
  id: z.string().min(1),
  brand: z.string().min(1),
  model: z.string().min(1),
  serial: z.string().min(1),
  type: z.string().default('B&N'),
  status: z.string().default('Usado'),
  machineCounter: z.number().int().default(0),
  clientId: z.string().nullable().optional(),
  abonoId: z.string().nullable().optional(),
  installationDate: z.string().nullable().optional(),
  initialCounter: z.number().int().default(0),
  applyIva: z.boolean().default(false),
  readingDay: z.number().int().default(10),
  isAvailable: z.boolean().default(true),
  pdfUrl: z.string().nullable().optional(),
  features: z.string().nullable().optional(),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const readingSyncSchema = z.object({
  id: z.string().min(1),
  machineId: z.string().min(1),
  clientId: z.string().min(1),
  abonoId: z.string().min(1),
  month: z.string().min(1),
  initial: z.number().int().default(0),
  final: z.number().int().default(0),
  readingStatus: z.string().default('Lectura tomada'),
  billingStatus: z.string().default('No facturado'),
  collectionStatus: z.string().default('Impago'),
  comments: z.string().nullable().optional(),
  invoiceNumber: z.string().nullable().optional(),
  invoiceDate: z.string().nullable().optional(),
  dueDate: z.string().nullable().optional(),
  paymentDate: z.string().nullable().optional(),
  paymentAmount: z.number().default(0),
  isUnofficial: z.boolean().default(false),
  creditNote: z.number().default(0),
  creditNoteReason: z.string().nullable().optional(),
  debitNote: z.number().default(0),
  debitNoteReason: z.string().nullable().optional(),
  invoiceFile: z.string().nullable().optional(),
  history: z.array(z.any()).default([]),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const ticketSyncSchema = z.object({
  id: z.string().min(1),
  clientType: z.string().default('existente'),
  clientId: z.string().nullable().optional(),
  clientName: z.string().min(1),
  clientAddress: z.string().nullable().optional(),
  clientPhone: z.string().nullable().optional(),
  clientEmail: z.string().nullable().optional(),
  clientContact: z.string().nullable().optional(),
  machineId: z.string().nullable().optional(),
  machineDesc: z.string().default('Equipo'),
  serialNumber: z.string().nullable().optional(),
  category: z.string().default('Servicio'),
  requestType: z.string().default('Telefono'),
  priority: z.string().default('Media'),
  status: z.string().default('nuevo'),
  description: z.string().default('Sin descripción'),
  diagnostic: z.string().nullable().optional(),
  partsNeeded: z.string().nullable().optional(),
  partsUsed: z.string().nullable().optional(),
  internalNotes: z.string().nullable().optional(),
  actionTaken: z.string().nullable().optional(),
  assignedTechId: z.string().nullable().optional(),
  technicalCost: z.number().nullable().optional(),
  observations: z.string().nullable().optional(),
  slaDate: dateSchema.nullable().optional(),
  resolvedAt: dateSchema.nullable().optional(),
  closedAt: dateSchema.nullable().optional(),
  history: z.array(z.any()).default([]),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const rentalSyncSchema = z.object({
  id: z.string().min(1),
  clientId: z.string().min(1),
  machineId: z.string().min(1),
  abonoId: z.string().min(1),
  startDate: z.string().min(1),
  endDate: z.string().nullable().optional(),
  status: z.string().default('activo'),
  observations: z.string().nullable().optional(),
  history: z.array(z.any()).default([]),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
});

export const budgetSyncSchema = z.object({
  id: z.string().min(1),
  numero: z.string().min(1),
  fecha: z.string().min(1),
  estado: z.string().default('borrador'),
  tipo: z.string().min(1),
  templateId: z.string().nullable().optional(),
  clientId: z.string().nullable().optional(),
  isNewClient: z.boolean().default(false),
  saveNewClient: z.boolean().default(false),
  ivaMode: z.string().default('ADD_21'),
  moneda: z.string().default('ARS'),
  subtotal: z.number().default(0),
  discountType: z.string().default('NONE'),
  discountValue: z.number().default(0),
  discountAmount: z.number().default(0),
  ivaAmount: z.number().default(0),
  total: z.number().default(0),
  validezOferta: z.string().default('15 Días'),
  plazoMinimoContrato: z.string().default('12 Meses'),
  ajustePrecios: z.string().default('Trimestral según IPC'),
  observaciones: z.string().nullable().optional(),
  introText: z.string().default(''),
  includesText: z.string().default(''),
  excludesText: z.string().default(''),
  requirementsText: z.string().default(''),
  conditionsText: z.string().default(''),
  footerText: z.string().default(''),
  clientSnapshot: z.any(),
  items: z.array(z.any()).default([]),
  machines: z.array(z.any()).default([]),
  sendLogs: z.array(z.any()).default([]),
  createdAt: dateSchema.optional(),
  updatedAt: dateSchema.optional(),
  issuedAt: dateSchema.nullable().optional(),
});

export const userSyncSchema = z.object({
  id: z.string().min(1),
  username: z.string().min(1),
  fullname: z.string().min(1),
  email: z.string().min(1),
  role: z.string().default('tecnico'),
  isMaster: z.number().int().default(0),
  phone: z.string().nullable().optional(),
  whatsapp: z.string().nullable().optional(),
  zone: z.string().nullable().optional(),
  specialty: z.string().nullable().optional(),
  availability: z.string().default('Disponible'),
  active: z.number().int().default(1),
  workHours: z.string().nullable().optional(),
  internalNotes: z.string().nullable().optional(),
});

export const syncQueueItemSchema = z.object({
  id: z.string().min(1),
  entityId: z.string().min(1),
  entityType: z.enum(['clients', 'machines', 'readings', 'tickets', 'plans', 'users', 'rentals', 'budgets']),
  operation: z.enum(['create', 'update', 'delete']),
  payload: z.any(),
  updatedAt: z.string(),
  status: z.enum(['pending', 'syncing', 'synced', 'failed']),
  retryCount: z.number().int().nonnegative().default(0),
});
